MenadzerZadan/Models/TaskModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MenadzerZadan.Models
{


        public class TaskModel : IValidatableObject
    {
        [Key]
        public int TaskId { get; set; }
        [Display(Name ="Nazwa:")]
        [Required(ErrorMessage = "Pole Nazwa jest wymagane.")]
        [MaxLength(50)]
        public string Name { get; set; }
        [Display(Name = "Opis:")]
        [MaxLength(2000)]
        public string Description { get; set; }
        public bool Done { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.Name == null) {
            yield return  new ValidationResult("Nie przekazałeś imienia", new string[] {"Imie"});
            }
        }
    }

    public class TasksContext : DbContext
    {
        public TasksContext() 
            : base("TasksConnectionString")
            {
            
            }
        public DbSet<TaskModel> TaskModels { get; set; }
    }
}

MenadzerZadan/Controllers/TaskController.cs
using MenadzerZadan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenadzerZadan.Controllers
{
    public class TaskController : Controller
    {
    
        public void AddToDatabase(TaskModel taskModel) { 

        TasksContext db = new TasksContext();
        db.TaskModels.Add(taskModel);
            db.SaveChanges();
        }

        private static IList<TaskModel> tasks = new List<TaskModel>()
        {
            new TaskModel(){ TaskId = 1, Name= "Wizyta u lekarza", Description= " Godzina 17:00", Done = false},
            new TaskModel(){ TaskId = 2, Name= "Zrobć obiad", Description= "Pierogi", Done = false},
        };
        
        //zmiana w pliku TaskController
        
        // GET: Task
        public ActionResult Index()
        {
            return View(tasks.Where(x => x.Done == false));
        }

        // GET: Task/Details/5
        public ActionResult Details(int id)
        {
            return View(tasks.FirstOrDefault(x => x.TaskId == id));
        }

        // GET: Task/Create
        public ActionResult Create()
        {
            return View(new TaskModel());
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult Create(TaskModel taskModel)
        {
            taskModel.TaskId = tasks.Count + 1; //dodanie ID zadania 
            // TODO: Add insert logic here
            tasks.Add(taskModel);

            
            

            return RedirectToAction("Index"); //przekierowuje do akcji
           
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int id)
        {
            return View(tasks.FirstOrDefault(x => x.TaskId == id));
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TaskModel taskModel)
        {
            TaskModel task = tasks.FirstOrDefault(x => x.TaskId == id);
            task.Name = taskModel.Name;
            task.Description = taskModel.Description;
                return RedirectToAction("Index");
          
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int id)
        {
            return View(tasks.FirstOrDefault(x => x.TaskId == id));
        }

        // POST: Task/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TaskModel taskModel)
        {
            TaskModel task = tasks.FirstOrDefault(x => x.TaskId == id);
            tasks.Remove(task);
            return RedirectToAction("Index");
            
        }
        // GET: Task/Done/5
        public ActionResult Done(int id)
        {
            TaskModel task = tasks.FirstOrDefault(x => x.TaskId == id);
            task.Done = true;

            return RedirectToAction("Index");
        }

    }
}

MenadzerZadan/Controllers/TaskModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MenadzerZadan.Models;

namespace MenadzerZadan.Controllers
{
    public class TaskModelsController : Controller
    {
        private TasksContext db = new TasksContext();



        // GET: TaskModels
        public ActionResult Index()
        {
            return View(db.TaskModels.Where(x => x.Done == false).ToList());
        }

        // GET: TaskModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskModel taskModel = db.TaskModels.Find(id);
            if (taskModel == null)
            {
                return HttpNotFound();
            }
            return View(taskModel);
        }

        // GET: TaskModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TaskModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskId,Name,Description,Done")] TaskModel taskModel)
        {
            if (ModelState.IsValid)
            {
                db.TaskModels.Add(taskModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taskModel);
        }

        // GET: TaskModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskModel taskModel = db.TaskModels.Find(id);
            if (taskModel == null)
            {
                return HttpNotFound();
            }
            return View(taskModel);
        }

        // POST: TaskModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TaskModel taskModel)
        {
            TaskModel task = db.TaskModels.FirstOrDefault(x => x.TaskId == id);
            task.Name = taskModel.Name;
            task.Description = taskModel.Description;
            db.SaveChanges();
            

            //return View("Index");
            return RedirectToAction("Index");
        }

        // GET: TaskModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskModel taskModel = db.TaskModels.Find(id);
            if (taskModel == null)
            {
                return HttpNotFound();
            }
            return View(taskModel);
        }

        // POST: TaskModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaskModel taskModel = db.TaskModels.Find(id);
            db.TaskModels.Remove(taskModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Task/Done/5
        public ActionResult Done(int id)
        {
            TaskModel taskModel = db.TaskModels.FirstOrDefault(x => x.TaskId == id);
            taskModel.Done = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MenadzerZadan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Menadżer zadań</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Menadżer zadań", "Index", "TaskModels", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Menadżer zadań by Szymon Fornal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MenadzerZadan/Views/Task/Create.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj zadanie</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy zadań", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MenadzerZadan/Views/Task/Delete.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń zadanie</h2>

<h3>Czy na pewno chcesz usunąć to zadanie?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
                <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

MenadzerZadan/Views/Task/Details.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły zadania</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new {  id = Model.TaskId  }) |
    @Html.ActionLink("Wróć do listy zadań", "Index")
</p>

MenadzerZadan/Views/Task/Edit.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edycja zadania</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wroc do Listy zadań", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MenadzerZadan/Views/Task/Index.cshtml
@model IEnumerable<MenadzerZadan.Models.TaskModel>

@{
    ViewBag.Title = "Index";
}

<h2>Lista zadań</h2>

<p>
    @Html.ActionLink("Dodaj zadanie", "Create", null, null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Gotowe", "Done", new { id = item.TaskId, @class = "btn btn-success" }) |
            @Html.ActionLink("Edytuj", "Edit", new { id = item.TaskId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id = item.TaskId }) |
            @Html.ActionLink("Usuń", "Delete", new { id = item.TaskId })
        </td>
    </tr>
}

</table>

MenadzerZadan/Views/TaskModels/Create.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj zadanie</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy zadań", "Index", null, null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MenadzerZadan/Views/TaskModels/Delete.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń zadanie</h2>

<h3>Czy na pewno chcesz usunąć to zadanie?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> 
            @Html.ActionLink("Wróć do listy", "Index", null, null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

MenadzerZadan/Views/TaskModels/Details.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły zadania</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.TaskId }, new { @class = "btn btn-warning" } ) 
    @Html.ActionLink("Wróć do listy zadań", "Index", null, null, new { @class = "btn btn-primary" })
</p>

MenadzerZadan/Views/TaskModels/Edit.cshtml
@model MenadzerZadan.Models.TaskModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edycja zadania</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wroc do Listy zadań", "Index", null, null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MenadzerZadan/Views/TaskModels/Index.cshtml
@model IEnumerable<MenadzerZadan.Models.TaskModel>

@{
    ViewBag.Title = "Index";
}

<h2 class="display-4">Lista zadań</h2>

<p>
    @Html.ActionLink("Dodaj zadanie", "Create", null, null, new { @class = "btn btn-primary" })
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Gotowe", "Done", new { id = item.TaskId }, new { @class = "btn btn-success" }) 
                @Html.ActionLink("Edytuj", "Edit", new { id = item.TaskId }, new { @class = "btn btn-info" }) 
                @Html.ActionLink("Szczegóły", "Details", new { id = item.TaskId }, new { @class = "btn btn-warning" }) 
                @Html.ActionLink("Usuń", "Delete", new { id = item.TaskId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>